### ISSUE TITLE
When looking for audio files, follow symlinks by default

### ISSUE THREAD

**Issue by iver56** [iver56/audiomentations#78]
Like https://github.com/asteroid-team/torch-audiomentations/pull/69

**Comment by abdallah1097** [comment]
Any idea why this error?

```bash
Abdallah@DESKTOP-G6QENGL MINGW64 /d/Work/GitHub Contributions/audiomentations/demo (master)
$ python demo.py
C:\ProgramData\Anaconda3\lib\site-packages\audiomentations\core\audio_loading_utils.py:64: UserWarning: D:\Work\GitHub Contributions\audiomentations\demo\background_noises\sheep.ogg had to be resampled from 44100 hz to 16000 hz. This hurt execution time.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\audiomentations\core\audio_loading_utils.py:64: UserWarning: D:\Work\GitHub Contributions\audiomentations\demo\background_noises\hens.ogg had to be resampled from 44100 hz to 16000 hz. This hurt execution time.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\audiomentations\core\audio_loading_utils.py:104: UserWarning: D:\Work\GitHub Contributions\audiomentations\demo\short_noises\friction0.wav had to be resampled from 44100 hz to 16000 hz. This hurt execution time.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\audiomentations\core\audio_loading_utils.py:104: UserWarning: D:\Work\GitHub Contributions\audiomentations\demo\short_noises\friction1.wav had to be resampled from 44100 hz to 16000 hz. This hurt execution time.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\pyloudnorm\normalize.py:62: UserWarning: Possible clipped samples in output.
  warnings.warn("Possible clipped samples in output.")
C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
Transforming acoustic_guitar_0.wav with shape (140544,)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\audio.py", line 146, in load
    with sf.SoundFile(path) as sf_desc:
  File "C:\ProgramData\Anaconda3\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "C:\ProgramData\Anaconda3\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'C:\\Users\\Abdallah\\AppData\\Local\\Temp\\tmp_compressed_6487c5c9-183.mp3': File contains data in an unknown format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 201, in <module>
    augmented_samples = augmenter(
  File "C:\ProgramData\Anaconda3\lib\site-packages\audiomentations\core\transforms_interface.py", line 76, in __call__
    return self.apply(samples, sample_rate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\audiomentations\augmentations\transforms.py", line 1054, in apply
    return self.apply_lameenc(samples, sample_rate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\audiomentations\augmentations\transforms.py", line 1096, in apply_lameenc
    degraded_samples, _ = librosa.load(tmp_file_path, sample_rate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\audio.py", line 163, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\audio.py", line 187, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\ProgramData\Anaconda3\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError
```

**Comment by iver56** [comment]
Have you tried googling it?

![bilde](https://user-images.githubusercontent.com/1470603/102266301-89e23380-3f18-11eb-94d8-661ef4819343.png)

**Comment by atamazian** [comment]
Can you assign me to this issue?
